import css from "./customToolbarStyles.module.css";
import bold from "../../images/customIcons/white/b.svg";
import boldGreen from "../../images/customIcons/green/b.svg";
import italic from "../../images/customIcons/white/i.svg";
import italicGreen from "../../images/customIcons/green/i.svg";

import underline from "../../images/customIcons/white/u.svg";
import underlineGreen from "../../images/customIcons/green/u.svg";


import h1 from "../../images/customIcons/white/ho.png";
import h1green from "../../images/customIcons/green/ho.png";
import h2 from "../../images/customIcons/white/hs.png";
import h2green from "../../images/customIcons/green/hs.png";



import ordered from "../../images/customIcons/white/numbr.png";
import orderedGreen from "../../images/customIcons/green/numbr.png";

import unordered from"../../images/customIcons/white/dots.png";
import unorderedGreen from "../../images/customIcons/green/dots.png";

import left from "../../images/customIcons/white/left.png";
import leftGreen from "../../images/customIcons/green/left.png";

import center from "../../images/customIcons/white/center.png";
import centerGreen from "../../images/customIcons/green/center.png";

import right from "../../images/customIcons/white/right.png";
import rightGreen from "../../images/customIcons/green/right.png";




//  * This is default toolbar configuration,
//  * whatever user passes in toolbar property is deeply merged with this to over-ride defaults.

//how to import images for onClick func
// iconOnClick: [""],=======================================how to import images localy with using classic path
// iconOnClick: [`${bold}`],================================how to use import with using $imported image
// iconOnClick: [boldGreen],================================in library(for devs)

export const toolbarOptions = {
  options: ["inline", "blockType", "list", "textAlign"],
  // options: [=============================================/default options
  //   "inline",
  //   "blockType",
  //   "fontSize",
  //   "fontFamily",
  //   "list",
  //   "textAlign",
  //   "colorPicker",
  //   "link",
  //   "embedded",
  //   "emoji",
  //   "image",
  //   "remove",
  //   "history",
  // ],
  inline: {
    inDropdown: false,
    className: undefined,
    component: undefined,
    dropdownClassName: undefined,
    options: [
      "bold",
      "italic",
      "underline",
      // "strikethrough",
      // "monospace",
      // "superscript",
      // "subscript",
    ],
    bold: {
      icon: bold,
      iconOnClick: [boldGreen],
      className: css.iconB,
      title: undefined,
    },
    italic: {
      icon: italic,
      iconOnClick: [italicGreen],
      className: css.Iconi,
      title: undefined,
    },
    underline: {
      icon: underline,
      iconOnClick: [underlineGreen],
      className: css.iconU,
      title: undefined,
    },
    strikethrough: {
      icon: undefined,
      className: undefined,
      title: undefined,
      iconOnClick: undefined,
    },
    monospace: { icon: undefined, className: undefined, title: undefined },
    superscript: { icon: undefined, className: undefined, title: undefined },
    subscript: { icon: undefined, className: undefined, title: undefined },
  },
  blockType: {
    inDropdown: false, //if true then just delete some strings if you need ti use it//
    // options: [
    //   "Normal",
    //   "H1",
    //   "H2",
    //   "H3",
    //   "H4",
    //   "H5",
    //   "H6",
    //   "Blockquote",
    //   "Code",
    // ],
    options: ["H1", "H2"],
    styleImagesWhenDropDownIsFalse: {
      Normal: {
        icon: undefined,
        iconOnClick: undefined,
        label: "Normal",
      },
      H1: {
        icon: h1,
        iconOnClick: [h1],
        label: "H1",
      },
      H2: {
        icon: h2,
        iconOnClick: [h2green],
        label: "H2",
      },
      H3: {
        icon: undefined,
        iconOnClick: undefined,
        label: "H3",
      },
      H4: {
        icon: undefined,
        iconOnClick: undefined,
        label: "H4",
      },
      H5: {
        icon: undefined,
        iconOnClick: undefined,
        label: "H5",
      },
      H6: {
        icon: undefined,
        iconOnClick: undefined,
        label: "H6",
      },
      Blockquote: {
        icon: undefined,
        iconOnClick: undefined,
        label: "Blockquote",
      },
      Code: { icon: undefined, iconOnClick: undefined, label: "Code" },
    },

    BlockQuote: { icon: undefined, className: undefined, title: undefined },
    Code: { icon: undefined, className: undefined, title: undefined },
    className: css.rdwlistwrapper,
    component: undefined,
    dropdownClassName: undefined,
    title: undefined,
  },
  fontSize: {
    icon: undefined,
    options: [8, 9, 10, 11, 12, 14, 16, 18, 24, 30, 36, 48, 60, 72, 96],
    className: undefined,
    component: undefined,
    dropdownClassName: undefined,
    title: undefined,
  },
  fontFamily: {
    options: [
      "Arial",
      "Georgia",
      "Impact",
      "Tahoma",
      "Times New Roman",
      "Verdana",
    ],
    className: undefined,
    component: undefined,
    dropdownClassName: undefined,
    title: undefined,
  },
  list: {
    inDropdown: false,
    className: undefined,
    component: undefined,
    dropdownClassName: undefined,
    options: ["unordered", "ordered"],
    // options: ["unordered", "ordered", "indent", "outdent"],
    unordered: {
      icon: unordered,
      iconOnClick: [unorderedGreen],
      className: css.iconDots,
      title: undefined,
    },
    ordered: {
      icon: ordered,
      iconOnClick: [orderedGreen],
      className: css.iconNumber,
      title: undefined,
    },
    indent: {
      icon: undefined,
      iconOnClick: undefined,
      className: undefined,
      title: undefined,
    },
    outdent: {
      icon: undefined,
      iconOnClick: undefined,
      className: undefined,
      title: undefined,
    },
    title: undefined,
  },
  textAlign: {
    inDropdown: false,
    className: undefined,
    component: undefined,
    dropdownClassName: undefined,
    options: ["left", "center", "right"],
    // options: ["left", "center", "right", "justify"],
    left: {
      icon:left,
      iconOnClick: [
        leftGreen
      ],
      className: css.textAlignLeft,
      title: undefined,
    },
    center: {
      icon: center,
      iconOnClick: [centerGreen],
      className: css.textAlignCenter,
      title: undefined,
    },
    right: {
      icon: right,
      iconOnClick: [rightGreen],
      className: css.textAlignRight,
      title: undefined,
    },
    justify: {
      icon: undefined,
      iconOnClick: undefined,
      className: undefined,
      title: undefined,
    },
    title: undefined,
  },
  colorPicker: {
    icon: undefined,
    className: undefined,
    component: undefined,
    popupClassName: undefined,
    colors: [
      "rgb(97,189,109)",
      "rgb(26,188,156)",
      "rgb(84,172,210)",
      "rgb(44,130,201)",
      "rgb(147,101,184)",
      "rgb(71,85,119)",
      "rgb(204,204,204)",
      "rgb(65,168,95)",
      "rgb(0,168,133)",
      "rgb(61,142,185)",
      "rgb(41,105,176)",
      "rgb(85,57,130)",
      "rgb(40,50,78)",
      "rgb(0,0,0)",
      "rgb(247,218,100)",
      "rgb(251,160,38)",
      "rgb(235,107,86)",
      "rgb(226,80,65)",
      "rgb(163,143,132)",
      "rgb(239,239,239)",
      "rgb(255,255,255)",
      "rgb(250,197,28)",
      "rgb(243,121,52)",
      "rgb(209,72,65)",
      "rgb(184,49,47)",
      "rgb(124,112,107)",
      "rgb(209,213,216)",
    ],
    title: undefined,
  },
  link: {
    inDropdown: false,
    className: undefined,
    component: undefined,
    popupClassName: undefined,
    dropdownClassName: undefined,
    showOpenOptionOnHover: true,
    defaultTargetOption: "_self",
    options: ["link", "unlink"],
    link: { icon: undefined, className: undefined, title: undefined },
    unlink: { icon: undefined, className: undefined, title: undefined },
    linkCallback: undefined,
  },
  emoji: {
    icon: undefined,
    className: undefined,
    component: undefined,
    popupClassName: undefined,
    emojis: [
      "😀",
      "😁",
      "😂",
      "😃",
      "😉",
      "😋",
      "😎",
      "😍",
      "😗",
      "🤗",
      "🤔",
      "😣",
      "😫",
      "😴",
      "😌",
      "🤓",
      "😛",
      "😜",
      "😠",
      "😇",
      "😷",
      "😈",
      "👻",
      "😺",
      "😸",
      "😹",
      "😻",
      "😼",
      "😽",
      "🙀",
      "🙈",
      "🙉",
      "🙊",
      "👼",
      "👮",
      "🕵",
      "💂",
      "👳",
      "🎅",
      "👸",
      "👰",
      "👲",
      "🙍",
      "🙇",
      "🚶",
      "🏃",
      "💃",
      "⛷",
      "🏂",
      "🏌",
      "🏄",
      "🚣",
      "🏊",
      "⛹",
      "🏋",
      "🚴",
      "👫",
      "💪",
      "👈",
      "👉",
      "👆",
      "🖕",
      "👇",
      "🖖",
      "🤘",
      "🖐",
      "👌",
      "👍",
      "👎",
      "✊",
      "👊",
      "👏",
      "🙌",
      "🙏",
      "🐵",
      "🐶",
      "🐇",
      "🐥",
      "🐸",
      "🐌",
      "🐛",
      "🐜",
      "🐝",
      "🍉",
      "🍄",
      "🍔",
      "🍤",
      "🍨",
      "🍪",
      "🎂",
      "🍰",
      "🍾",
      "🍷",
      "🍸",
      "🍺",
      "🌍",
      "🚑",
      "⏰",
      "🌙",
      "🌝",
      "🌞",
      "⭐",
      "🌟",
      "🌠",
      "🌨",
      "🌩",
      "⛄",
      "🔥",
      "🎄",
      "🎈",
      "🎉",
      "🎊",
      "🎁",
      "🎗",
      "🏀",
      "🏈",
      "🎲",
      "🔇",
      "🔈",
      "📣",
      "🔔",
      "🎵",
      "🎷",
      "💰",
      "🖊",
      "📅",
      "✅",
      "❎",
      "💯",
    ],
    title: undefined,
  },
  embedded: {
    icon: undefined,
    className: undefined,
    component: undefined,
    popupClassName: undefined,
    embedCallback: undefined,
    defaultSize: {
      height: "auto",
      width: "auto",
    },
    title: undefined,
  },
  image: {
    icon: undefined,
    className: undefined,
    component: undefined,
    popupClassName: undefined,
    urlEnabled: true,
    uploadEnabled: true,
    previewImage: false,
    alignmentEnabled: true,
    uploadCallback: undefined,
    inputAccept: "image/gif,image/jpeg,image/jpg,image/png,image/svg",
    alt: { present: false, mandatory: false },
    defaultSize: {
      height: "auto",
      width: "auto",
    },
    title: undefined,
  },
  remove: {
    icon: undefined,
    className: undefined,
    component: undefined,
    title: undefined,
  },
  history: {
    inDropdown: false,
    className: undefined,
    component: undefined,
    dropdownClassName: undefined,
    options: ["undo", "redo"],
    undo: { icon: undefined, className: undefined, title: undefined },
    redo: { icon: undefined, className: undefined, title: undefined },
    title: undefined,
  },
};
